### ISSUE TITLE
send empty json instead of empty json array if no request payload 

### ISSUE THREAD

**Issue by chaouchAbderraouf** [evaisse/SimpleHttpBundle#12]
If the request payload is empty , a json array "[]" is sent as request content . 
Shouldn't be an empty json  ""  instead ? 

https://github.com/evaisse/SimpleHttpBundle/blob/master/Http/Statement.php#L242

**Comment by evaisse** [comment]
An empty string is not a valid JSON content-type. We should have to remove the assigned content-type. 

I will probably distinguish the usage of the `->json(null)` call by using `func_num_args` to allow user to be able to send "null" value or anything he wants.
And I probably prefer to use `{}` content body if there his no request params, to keep the body type heterogeneous and the behavior consistent. And eventually "null" is nocurrently the best option right ? or
